#!/bin/bash

getent passwd {1000..60000} | cut -d: -f1

# Normal users are the users created by the root or another user with sudo privileges.
# Usually, a normal user has a real login shell and a home directory.

# Each user has a numeric user ID called UID. If not specified when creating a new user
# with the useradd command, the UID will be automatically selected from the /etc/login.defs
# file depending on the UID_MIN and UID_MIN values.
# To check the UID_MIN and UID_MIN values on your system you can use the following command:
# grep -E '^UID_MIN|^UID_MAX' /etc/login.defs